name: CI - Build & Run Docker Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ci-cd .

      - name: Run container in background
        run: docker run -d -p 3000:3000 --name ci-cd ci-cd

      - name: Wait for container to start
        run: sleep 5

      - name: Test if container is running
        run: curl -f http://localhost:3000

      - name: Stop container
        run: docker stop ci-cd

      - name: Remove container
        run: docker rm ci-cd


# name: Deploy to Cloud Run

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v4

#       - name: Set up gcloud
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           project_id: ${{ secrets.GCP_PROJECT_ID }}

#       - name: Configure Docker for Artifact Registry
#         run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ci-cd-repo/ci-cd:latest .

#       - name: Push Docker image
#         run: |
#           docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ci-cd-repo/ci-cd:latest

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud run deploy ci-cd-demo \
#             --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ci-cd-repo/ci-cd:latest \
#             --platform=managed \
#             --region=${{ secrets.GCP_REGION }} \
#             --allow-unauthenticated